/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MovieIdImport } from './routes/$movieId'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const MovieIdRoute = MovieIdImport.update({
  id: '/$movieId',
  path: '/$movieId',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$movieId': {
      id: '/$movieId'
      path: '/$movieId'
      fullPath: '/$movieId'
      preLoaderRoute: typeof MovieIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$movieId': typeof MovieIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$movieId': typeof MovieIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$movieId': typeof MovieIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$movieId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$movieId'
  id: '__root__' | '/' | '/$movieId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MovieIdRoute: typeof MovieIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MovieIdRoute: MovieIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$movieId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$movieId": {
      "filePath": "$movieId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
